#include "arcsync.h"

#include <stdio.h>
#include <string.h>
#include <time.h>

static const char *CSS =
"body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"
"margin:0;padding:1.25rem;background:#f6f4f1;color:#1c1917;}"
"a{color:#1d4ed8;text-decoration:none}a:hover{text-decoration:underline}"
"h1{font-size:1.5rem;margin:0 0 .5rem}h2{font-size:1.15rem}"
".meta{color:#57534e;font-size:.9rem;margin-bottom:1.25rem}"
".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:.75rem}"
".tile{background:#fff;border:1px solid #e7e5e4;border-radius:.5rem;overflow:hidden}"
".tile img{display:block;width:100%;height:140px;object-fit:cover;background:#e7e5e4}"
".tile .cap{padding:.4rem .55rem;font-size:.75rem;color:#44403c;"
"white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
"nav a{margin-right:1rem}";

static void
write_css(const char *stage)
{
	char path[4096];
	FILE *fp;
	arcsync_path_join(path, sizeof(path), stage, "css");
	arcsync_mkdir_p(path);
	arcsync_path_join(path, sizeof(path), stage, "css/style.css");
	fp = fopen(path, "w");
	if (!fp)
		return;
	fputs(CSS, fp);
	fclose(fp);
}

static void
write_readme(const char *stage, const arcsync_opts_t *opts)
{
	char path[4096];
	FILE *fp;
	arcsync_path_join(path, sizeof(path), stage, "README.txt");
	fp = fopen(path, "w");
	if (!fp)
		return;
	fprintf(fp,
	    "ArcSync photo archive\n"
	    "=====================\n\n"
	    "Open index.html in a web browser to browse this disc.\n"
	    "Original media files are under media/YYYY/MM/DD/.\n"
	    "HEIC photos may need a codec on older Windows systems.\n\n"
	    "Title: %s\n"
	    "Generated by arcsync %s\n",
	    opts->title ? opts->title : "ArcSync", ARCSYNC_VERSION);
	fclose(fp);
}

static void
write_autorun(const char *stage, const arcsync_opts_t *opts)
{
	char path[4096];
	FILE *fp;
	arcsync_path_join(path, sizeof(path), stage, "autorun.inf");
	fp = fopen(path, "w");
	if (!fp)
		return;
	fprintf(fp,
	    "[autorun]\n"
	    "label=%s\n"
	    "shellexecute=index.html\n"
	    "action=Open photo archive\n",
	    opts->volume_name ? opts->volume_name : "ARCSYNC");
	fclose(fp);
}

static void
tile(FILE *fp, const arcsync_asset_t *a)
{
	fprintf(fp, "<a class=\"tile\" href=\"");
	arcsync_html_escape(fp, a->dest_rel);
	fprintf(fp, "\"><img src=\"");
	arcsync_html_escape(fp, a->thumb_rel ? a->thumb_rel : "");
	fprintf(fp, "\" alt=\"");
	arcsync_html_escape(fp, a->orig_name);
	fprintf(fp, "\"><div class=\"cap\">");
	arcsync_html_escape(fp, a->orig_name);
	fprintf(fp, "</div></a>\n");
}

int
arcsync_write_html(const arcsync_catalog_t *cat, const arcsync_stage_t *st,
    const arcsync_opts_t *opts, int disc_n, int disc_m, uint64_t vol_bytes)
{
	char path[4096];
	FILE *fp;
	size_t i, shown;
	time_t now = time(NULL);
	char nowbuf[64];
	struct tm tmnow;

	write_css(st->stage_root);
	write_readme(st->stage_root, opts);
	write_autorun(st->stage_root, opts);

	localtime_r(&now, &tmnow);
	strftime(nowbuf, sizeof(nowbuf), "%Y-%m-%d %H:%M", &tmnow);

	/* index.html */
	arcsync_path_join(path, sizeof(path), st->stage_root, "index.html");
	fp = fopen(path, "w");
	if (!fp)
		return 4;
	fprintf(fp,
	    "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
	    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
	    "<title>");
	arcsync_html_escape(fp, opts->title);
	fprintf(fp, "</title><link rel=\"stylesheet\" href=\"css/style.css\"></head><body>\n");
	fprintf(fp, "<h1>");
	arcsync_html_escape(fp, opts->title);
	fprintf(fp, "</h1>\n");
	if (disc_m > 1)
		fprintf(fp, "<p class=\"meta\">Disc %d of %d</p>\n", disc_n, disc_m);
	fprintf(fp, "<p class=\"meta\">Generated %s · %zu photos · %zu videos · %.1f MiB</p>\n",
	    nowbuf, cat->n_photos, cat->n_videos, vol_bytes / (1024.0 * 1024.0));
	fprintf(fp, "<nav><a href=\"albums/index.html\">Albums</a>"
	    "<a href=\"by-date/index.html\">By date</a>"
	    "<a href=\"README.txt\">README</a></nav>\n");
	fprintf(fp, "<h2>Sampler</h2><div class=\"grid\">\n");
	for (i = 0, shown = 0; i < cat->n_assets && shown < 40; i++) {
		if (cat->assets[i].missing)
			continue;
		tile(fp, &cat->assets[i]);
		shown++;
	}
	fprintf(fp, "</div></body></html>\n");
	fclose(fp);

	/* open-me.html alias */
	arcsync_path_join(path, sizeof(path), st->stage_root, "open-me.html");
	fp = fopen(path, "w");
	if (fp) {
		fputs("<!DOCTYPE html><meta charset=\"utf-8\">"
		    "<meta http-equiv=\"refresh\" content=\"0;url=index.html\">"
		    "<a href=\"index.html\">Open archive</a>\n", fp);
		fclose(fp);
	}

	/* albums/index.html */
	arcsync_path_join(path, sizeof(path), st->stage_root, "albums");
	arcsync_mkdir_p(path);
	arcsync_path_join(path, sizeof(path), st->stage_root, "albums/index.html");
	fp = fopen(path, "w");
	if (!fp)
		return 4;
	fprintf(fp, "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
	    "<title>Albums</title><link rel=\"stylesheet\" href=\"../css/style.css\">"
	    "</head><body><h1>Albums</h1><p><a href=\"../index.html\">Home</a></p><ul>\n");
	for (i = 0; i < cat->n_albums; i++) {
		fprintf(fp, "<li><a href=\"");
		arcsync_html_escape(fp, cat->albums[i].slug);
		fprintf(fp, "/index.html\">");
		arcsync_html_escape(fp, cat->albums[i].title);
		fprintf(fp, "</a> (%zu)</li>\n", cat->albums[i].n_assets);
	}
	fprintf(fp, "</ul></body></html>\n");
	fclose(fp);

	for (i = 0; i < cat->n_albums; i++) {
		const arcsync_album_t *alb = &cat->albums[i];
		char apath[4096];
		size_t j;
		snprintf(apath, sizeof(apath), "%s/albums/%s", st->stage_root, alb->slug);
		arcsync_mkdir_p(apath);
		snprintf(apath, sizeof(apath), "%s/albums/%s/index.html", st->stage_root, alb->slug);
		fp = fopen(apath, "w");
		if (!fp)
			return 4;
		fprintf(fp, "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>");
		arcsync_html_escape(fp, alb->title);
		fprintf(fp, "</title><link rel=\"stylesheet\" href=\"../../css/style.css\">"
		    "</head><body><h1>");
		arcsync_html_escape(fp, alb->title);
		fprintf(fp, "</h1><p><a href=\"../index.html\">Albums</a> · "
		    "<a href=\"../../index.html\">Home</a></p><div class=\"grid\">\n");
		for (j = 0; j < alb->n_assets; j++) {
			const arcsync_asset_t *a = &cat->assets[alb->asset_idx[j]];
			/* fix relative hrefs from albums/<slug>/ */
			fprintf(fp, "<a class=\"tile\" href=\"../../");
			arcsync_html_escape(fp, a->dest_rel);
			fprintf(fp, "\"><img src=\"../../");
			arcsync_html_escape(fp, a->thumb_rel ? a->thumb_rel : "");
			fprintf(fp, "\" alt=\"");
			arcsync_html_escape(fp, a->orig_name);
			fprintf(fp, "\"><div class=\"cap\">");
			arcsync_html_escape(fp, a->orig_name);
			fprintf(fp, "</div></a>\n");
		}
		fprintf(fp, "</div></body></html>\n");
		fclose(fp);
	}

	/* by-date stub */
	arcsync_path_join(path, sizeof(path), st->stage_root, "by-date");
	arcsync_mkdir_p(path);
	arcsync_path_join(path, sizeof(path), st->stage_root, "by-date/index.html");
	fp = fopen(path, "w");
	if (fp) {
		fprintf(fp, "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
		    "<title>By date</title><link rel=\"stylesheet\" href=\"../css/style.css\">"
		    "</head><body><h1>By date</h1><p><a href=\"../index.html\">Home</a></p>"
		    "<p class=\"meta\">Browse folders under <code>media/YYYY/MM/DD/</code>.</p>"
		    "<div class=\"grid\">\n");
		for (i = 0, shown = 0; i < cat->n_assets && shown < 80; i++) {
			fprintf(fp, "<a class=\"tile\" href=\"../");
			arcsync_html_escape(fp, cat->assets[i].dest_rel);
			fprintf(fp, "\"><img src=\"../");
			arcsync_html_escape(fp, cat->assets[i].thumb_rel);
			fprintf(fp, "\" alt=\"\"><div class=\"cap\">");
			arcsync_html_escape(fp, cat->assets[i].dest_rel);
			fprintf(fp, "</div></a>\n");
			shown++;
		}
		fprintf(fp, "</div></body></html>\n");
		fclose(fp);
	}

	if (!opts->quiet)
		fprintf(stderr, "arcsync: html     %zu album pages\n", cat->n_albums);
	return 0;
}

int
arcsync_write_sidecar(const arcsync_catalog_t *cat, const arcsync_stage_t *st,
    const arcsync_opts_t *opts)
{
	char path[4096];
	FILE *fp;
	size_t i;
	(void)opts;

	arcsync_path_join(path, sizeof(path), st->stage_root, "manifest.tsv");
	fp = fopen(path, "w");
	if (!fp)
		return 4;
	fprintf(fp, "id\tdate\talbum\tdest\tbytes\tkind\tquality\n");
	for (i = 0; i < cat->n_assets; i++) {
		const arcsync_asset_t *a = &cat->assets[i];
		struct tm tm;
		char dbuf[32];
		localtime_r(&a->captured, &tm);
		strftime(dbuf, sizeof(dbuf), "%Y-%m-%d", &tm);
		fprintf(fp, "%s\t%s\t%s\t%s\t%llu\t%s\t%s\n",
		    a->id ? a->id : "",
		    dbuf,
		    a->album_title ? a->album_title : "",
		    a->dest_rel ? a->dest_rel : "",
		    (unsigned long long)a->bytes,
		    a->kind == ARCSYNC_KIND_VIDEO ? "video" : "photo",
		    a->missing ? "missing" : (a->derivative ? "derivative" : "original"));
	}
	fclose(fp);

	arcsync_path_join(path, sizeof(path), st->stage_root, "missing.txt");
	fp = fopen(path, "w");
	if (!fp)
		return 4;
	fprintf(fp, "# assets not present as local originals\n");
	for (i = 0; i < cat->n_assets; i++) {
		if (cat->assets[i].missing)
			fprintf(fp, "%s\t%s\n", cat->assets[i].id, cat->assets[i].src_path);
	}
	fclose(fp);
	return 0;
}
